export type DbProductRow = {
  id: string;
  name: string;
  slug: string;
  sku: string;
  category_id: string;
  subcategory_id: string | null;
  brand_id: string;
  price: number;
  compare_at_price: number | null;
  stock: number;
  images: string[];
  short_description: string;
  description: string;
  features: string[];
  specifications: Record<string, string>;
  warranty: string | null;
  shipping_info: string | null;
  is_featured: boolean;
  is_available: boolean;
  is_new: boolean;
  is_best_seller: boolean;
  rating: number;
  review_count: number;
  created_at: string;
  updated_at: string;
  categories: { name: string; slug: string } | null;
  subcategories: { name: string; slug: string } | null;
  brands: { name: string; slug: string } | null;
};

export type ProductInput = {
  name: string;
  slug?: string;
  sku: string;
  categoryId: string;
  subcategoryId?: string | null;
  brandId: string;
  price: number;
  compareAtPrice?: number | null;
  stock: number;
  images: string[];
  shortDescription: string;
  description: string;
  features: string[];
  specifications: Record<string, string>;
  warranty?: string;
  shippingInfo?: string;
  isFeatured: boolean;
  isAvailable: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
};
